### ISSUE TITLE
회원 수정 요청 시, Null 값이 반영되는 문제

### ISSUE THREAD

**Issue by hamsteak1488** [BackendTheBone/MiraeCommerce#1]
## 목적
>컨트롤러에 회원 수정 요청을 보낼 시, 요청 객체 필드에 null이 들어갈 경우 회원 엔티티의 해당 필드가 null이 되어버림
## 작업 상세 내용
- [x] @DynamicUpdate 동작이 왜 잘못되었는지 확인하고 수정할 것
## 참고 사항
@DynamicUpdate를 Entity에 달아둘 경우 Jpa로 save할 때, null 필드는 update에 반영하지 않는다고 배웠다.

**Comment by kimdw524** [comment]
안녕

**Comment by kimdw524** [comment]
그건 큰 문제입니다
